/*
 * Copyright 2025 Uber Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** @file testGeodesicGridDiskRoundtrip.c
 * @brief Tests that geodesic polygonToCellsExperimental with
 *        CONTAINMENT_OVERLAPPING | FLAG_GEODESIC correctly recovers cells
 *        from polygons generated by cellsToMultiPolygon.
 */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "h3Index.h"
#include "iterators.h"
#include "test.h"
#include "vec3d.h"

#define TRACE_VEC_MATCH_TOL 1e-12

typedef struct {
    int missingCells;
    int skippedCases;
    int internalErrors;
} RoundtripStats;

typedef struct {
    const char *name;
    int res;
    int k;
} ExhaustiveConfig;

static double vec3Distance(const Vec3d *a, const Vec3d *b) {
    const double dx = a->x - b->x;
    const double dy = a->y - b->y;
    const double dz = a->z - b->z;
    return sqrt(dx * dx + dy * dy + dz * dz);
}

static int64_t compactNonZeroCells(H3Index *cells, int64_t count) {
    int64_t out = 0;
    for (int64_t i = 0; i < count; i++) {
        if (cells[i] != H3_NULL) {
            cells[out++] = cells[i];
        }
    }
    return out;
}

static int traceCellBoundaryPathMismatch(H3Index cell) {
    CellBoundary latLngBoundary = {0};
    GeodesicCellBoundary geodesicBoundary = {0};

    if (H3_EXPORT(cellToBoundary)(cell, &latLngBoundary) != E_SUCCESS ||
        H3_EXPORT(cellToGeodesicBoundary)(cell, &geodesicBoundary) !=
            E_SUCCESS) {
        fprintf(stderr,
                "    unable to trace boundary path mismatch for 0x%llx\n",
                (unsigned long long)cell);
        return 1;
    }

    fprintf(stderr, "    cell boundary path comparison for 0x%llx:\n",
            (unsigned long long)cell);
    for (int i = 0; i < latLngBoundary.numVerts; i++) {
        Vec3d viaGeo;
        _geoToVec3d(&latLngBoundary.verts[i], &viaGeo);

        const double dist = vec3Distance(&viaGeo, &geodesicBoundary.verts[i]);
        fprintf(stderr,
                "      vert[%d]: dist(_geoToVec3d(cellToBoundary), "
                "cellToGeodesicBoundary)=%.3e\n",
                i, dist);
    }

    return 0;
}

static int traceMissingCellAgainstPolygon(const GeoPolygon *polygon,
                                          H3Index missingCell) {
    GeodesicCellBoundary cellBoundary = {0};
    if (H3_EXPORT(cellToGeodesicBoundary)(missingCell, &cellBoundary) !=
        E_SUCCESS) {
        fprintf(stderr,
                "    unable to trace missing cell boundary for 0x%llx\n",
                (unsigned long long)missingCell);
        return 1;
    }

    const GeoLoop *loop = &polygon->geoloop;
    Vec3d *polyVerts = calloc(loop->numVerts, sizeof(Vec3d));
    if (polyVerts == NULL) {
        fprintf(stderr, "    alloc failure while tracing missing cell 0x%llx\n",
                (unsigned long long)missingCell);
        return 1;
    }

    for (int i = 0; i < loop->numVerts; i++) {
        _geoToVec3d(&loop->verts[i], &polyVerts[i]);
    }

    fprintf(stderr, "    nearest polygon vertex for missing cell 0x%llx:\n",
            (unsigned long long)missingCell);
    for (int i = 0; i < cellBoundary.numVerts; i++) {
        int nearestIndex = -1;
        double nearestDist = INFINITY;
        for (int j = 0; j < loop->numVerts; j++) {
            const double dist =
                vec3Distance(&cellBoundary.verts[i], &polyVerts[j]);
            if (dist < nearestDist) {
                nearestDist = dist;
                nearestIndex = j;
            }
        }

        fprintf(stderr, "      cell vert[%d] -> poly vert[%d], dist=%.3e\n", i,
                nearestIndex, nearestDist);
    }

    fprintf(stderr,
            "    near-coincident edge traces (_geodesicEdgesCross inputs):\n");
    for (int j = 0; j < cellBoundary.numVerts; j++) {
        const int nextJ = (j + 1) % cellBoundary.numVerts;
        Vec3d normalA;
        vec3Cross(&cellBoundary.verts[j], &cellBoundary.verts[nextJ], &normalA);

        for (int i = 0; i < loop->numVerts; i++) {
            const int nextI = (i + 1) % loop->numVerts;

            const double d00 =
                vec3Distance(&cellBoundary.verts[j], &polyVerts[i]);
            const double d11 =
                vec3Distance(&cellBoundary.verts[nextJ], &polyVerts[nextI]);
            const double d01 =
                vec3Distance(&cellBoundary.verts[j], &polyVerts[nextI]);
            const double d10 =
                vec3Distance(&cellBoundary.verts[nextJ], &polyVerts[i]);

            if (!((d00 < TRACE_VEC_MATCH_TOL && d11 < TRACE_VEC_MATCH_TOL) ||
                  (d01 < TRACE_VEC_MATCH_TOL && d10 < TRACE_VEC_MATCH_TOL))) {
                continue;
            }

            Vec3d normalB;
            vec3Cross(&polyVerts[i], &polyVerts[nextI], &normalB);

            const double b1Side = vec3Dot(&normalA, &polyVerts[i]);
            const double b2Side = vec3Dot(&normalA, &polyVerts[nextI]);
            const double a1Side = vec3Dot(&normalB, &cellBoundary.verts[j]);
            const double a2Side = vec3Dot(&normalB, &cellBoundary.verts[nextJ]);
            const double bProd = b1Side * b2Side;
            const double aProd = a1Side * a2Side;
            const int rejected = (bProd > 0) || (aProd > 0);

            fprintf(stderr,
                    "      poly[%d] x cell[%d]: "
                    "d00=%.3e d11=%.3e d01=%.3e d10=%.3e "
                    "b1Side=%.3e b2Side=%.3e a1Side=%.3e a2Side=%.3e\n",
                    i, j, d00, d11, d01, d10, b1Side, b2Side, a1Side, a2Side);
            fprintf(stderr, "        -> %s: bProd=%.3e aProd=%.3e\n",
                    rejected ? "REJECTED (same side)" : "candidate crossing",
                    bProd, aProd);
        }
    }

    free(polyVerts);
    return 0;
}

/* ------------------------------------------------------------------ */
/*  Helper: run the roundtrip check for one (cell, k) pair.           */
/*  Updates aggregate stats instead of asserting internally.          */
/* ------------------------------------------------------------------ */
static void gridDiskRoundtripCheck(H3Index center, int k,
                                   RoundtripStats *stats) {
    int res = H3_GET_RESOLUTION(center);

    /* 1. Build grid disk ------------------------------------------- */
    int64_t diskMax;
    if (H3_EXPORT(maxGridDiskSize)(k, &diskMax) != E_SUCCESS) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - maxGridDiskSize failed\n",
                (unsigned long long)center, k, res);
        stats->internalErrors++;
        return;
    }
    H3Index *disk = calloc(diskMax, sizeof(H3Index));
    if (disk == NULL) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - alloc disk failed\n",
                (unsigned long long)center, k, res);
        stats->internalErrors++;
        return;
    }
    if (H3_EXPORT(gridDisk)(center, k, disk) != E_SUCCESS) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - gridDisk failed\n",
                (unsigned long long)center, k, res);
        free(disk);
        stats->internalErrors++;
        return;
    }
    const int64_t diskCount = compactNonZeroCells(disk, diskMax);

    /* 2. Cells -> polygon ------------------------------------------ */
    GeoMultiPolygon mpoly = {0};
    if (H3_EXPORT(cellsToMultiPolygon)(disk, diskCount, &mpoly) != E_SUCCESS) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - cellsToMultiPolygon "
                "failed\n",
                (unsigned long long)center, k, res);
        free(disk);
        stats->internalErrors++;
        return;
    }

    /*
     * Skip cases where the disk doesn't form a single simple polygon.
     * This can happen for grid disks that span more than a hemisphere
     * at very low resolutions.
     */
    if (mpoly.numPolygons != 1 || mpoly.polygons[0].numHoles != 0) {
        H3_EXPORT(destroyGeoMultiPolygon)(&mpoly);
        free(disk);
        stats->skippedCases++;
        return;
    }

    /* 3. Geodesic polyfill ----------------------------------------- */
    uint32_t flags = CONTAINMENT_OVERLAPPING;
    FLAG_SET_GEODESIC(flags);

    int64_t outMax = 0;
    if (H3_EXPORT(maxPolygonToCellsSizeExperimental)(
            &mpoly.polygons[0], res, flags, &outMax) != E_SUCCESS) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - "
                "maxPolygonToCellsSizeExperimental failed\n",
                (unsigned long long)center, k, res);
        H3_EXPORT(destroyGeoMultiPolygon)(&mpoly);
        free(disk);
        stats->internalErrors++;
        return;
    }

    H3Index *out = calloc(outMax, sizeof(H3Index));
    if (out == NULL) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - alloc out failed\n",
                (unsigned long long)center, k, res);
        H3_EXPORT(destroyGeoMultiPolygon)(&mpoly);
        free(disk);
        stats->internalErrors++;
        return;
    }
    if (H3_EXPORT(polygonToCellsExperimental)(&mpoly.polygons[0], res, flags,
                                              outMax, out) != E_SUCCESS) {
        fprintf(stderr,
                "  ERROR: center=0x%llx k=%d res=%d - "
                "polygonToCellsExperimental failed\n",
                (unsigned long long)center, k, res);
        H3_EXPORT(destroyGeoMultiPolygon)(&mpoly);
        free(out);
        free(disk);
        stats->internalErrors++;
        return;
    }

    /* 4. Check superset property: every disk cell must be in out ---- */
    for (int64_t i = 0; i < diskCount; i++) {
        int found = 0;
        for (int64_t j = 0; j < outMax; j++) {
            if (out[j] == disk[i]) {
                found = 1;
                break;
            }
        }
        if (!found) {
            stats->missingCells++;
            fprintf(stderr,
                    "  FAIL: center=0x%llx k=%d res=%d - "
                    "missing cell 0x%llx\n",
                    (unsigned long long)center, k, res,
                    (unsigned long long)disk[i]);
            stats->internalErrors += traceCellBoundaryPathMismatch(disk[i]);
            stats->internalErrors +=
                traceMissingCellAgainstPolygon(&mpoly.polygons[0], disk[i]);
        }
    }

    H3_EXPORT(destroyGeoMultiPolygon)(&mpoly);
    free(out);
    free(disk);
}

static void runExhaustiveConfig(const ExhaustiveConfig *config,
                                RoundtripStats *stats) {
    for (IterCellsResolution it = iterInitRes(config->res); it.h;
         iterStepRes(&it)) {
        gridDiskRoundtripCheck(it.h, config->k, stats);
    }
}

/* ------------------------------------------------------------------ */
/*  Test suite                                                         */
/* ------------------------------------------------------------------ */
SUITE(GeodesicGridDiskRoundtrip) {
    TEST(exhaustiveCoverageMatrix) {
        const ExhaustiveConfig configs[] = {{"res0k0", 0, 0}, {"res0k1", 0, 1},
                                            {"res0k2", 0, 2}, {"res1k0", 1, 0},
                                            {"res1k1", 1, 1}, {"res2k0", 2, 0}};
        // {"res1k2", 1, 2},
        // {"res2k0", 2, 0}, {"res2k1", 2, 1},
        // {"res2k2", 2, 2}, {"res3k0", 3, 0}};
        // You are welcome to test more, but that will take time
        RoundtripStats total = {0};

        for (int i = 0; i < (int)(sizeof(configs) / sizeof(configs[0])); i++) {
            RoundtripStats stats = {0};
            runExhaustiveConfig(&configs[i], &stats);
            total.missingCells += stats.missingCells;
            total.skippedCases += stats.skippedCases;
            total.internalErrors += stats.internalErrors;
            fprintf(stderr,
                    "  exhaustive %s: missing=%d skipped=%d errors=%d\n",
                    configs[i].name, stats.missingCells, stats.skippedCases,
                    stats.internalErrors);
        }

        t_assert(total.internalErrors == 0,
                 "exhaustive configs should not hit helper errors");
        t_assert(total.missingCells == 0,
                 "all exhaustive res/k configs should round-trip");
    }
}
